import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { useContext, useEffect, useState } from "react";
import { AuthContext } from "../context/AuthContext";
import { signOut, onAuthStateChanged } from "firebase/auth";
import { auth, db } from "../firebaseConfig";
import { doc, getDoc } from "firebase/firestore";

export default function Home() {
  const router = useRouter();
  const { loggedInUser, getProductList, products } = useContext(AuthContext);

  console.log(products);

  // useEffect(() => {
  //   getProductList();
  // }, []);

  const handleLogOut = (e) => {
    signOut(auth);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{loggedInUser?.displayName}</h1>
        <button onClick={handleLogOut}>Log Out</button>
      </main>
    </div>
  );
}
